package opengl.Palette
--
--  Provides a pallete of named colors.
--
--  Color values are sourced from WikiPaedia:
--
--    - http://en.wikipedia.org/wiki/Primary_color
--    - http://en.wikipedia.org/wiki/Secondary_color
--    - http://en.wikipedia.org/wiki/Tertiary_color
--    - http://en.wikipedia.org/wiki/List_of_colors
--
is
   --------------------
   --  Color Primitives
   --------------------

   --  Shades
   --
   type shade_Level is digits 7 range 0.0 .. 1.0;

   function Shade_of (Self : in Color;   Level : in shade_Level) return Color;
   --
   --  Darkens a color by the given shade level factor.


   --  Color Mixing
   --

   function Mixed (Self : in Color;   Other : in Color) return Color;
   --
   --  Combines two colors.


   --  Similarity
   --
   function is_Similar (Self : in Color;   To         : in Color;
                                           Similarity : in color_Value := 3) return Boolean;


   --  Random Colors
   --
   function random_Color return Color;



   ----------------
   --  Named Colors
   ----------------

   --  Achromatic
   --
   White : constant Color;
   Black : constant Color;
   Grey  : constant Color;

   --  Primary
   --
   Red   : constant Color;
   Green : constant Color;
   Blue  : constant Color;

   --  Secondary
   --
   Yellow  : constant Color;
   Cyan    : constant Color;
   Magenta : constant Color;

   --  Tertiary
   --
   Azure        : constant Color;
   Violet       : constant Color;
   Rose         : constant Color;
   Orange       : constant Color;
   Chartreuse   : constant Color;
   spring_Green : constant Color;


   --  Named (tbd: sort named colors into primary, secondary or tertiary categories).
   --
   Air_Force_blue           : constant Color;
   Alice_blue               : constant Color;
   Alizarin                 : constant Color;
   Amaranth                 : constant Color;
   Amaranth_cerise          : constant Color;
   Amaranth_deep_purple     : constant Color;
   Amaranth_magenta         : constant Color;
   Amaranth_pink            : constant Color;
   Amaranth_purple          : constant Color;
   Amber                    : constant Color;
   Amber_SAE_ECE            : constant Color;
   American_rose            : constant Color;
   Amethyst                 : constant Color;
   Android_Green            : constant Color;
   Anti_flash_white         : constant Color;
   Antique_fuchsia          : constant Color;
   Antique_white            : constant Color;
   Apple_green              : constant Color;
   Apricot                  : constant Color;
   Aqua                     : constant Color;
   Aquamarine               : constant Color;
   Army_green               : constant Color;
   Arsenic                  : constant Color;
   Ash_grey                 : constant Color;
   Asparagus                : constant Color;
   Atomic_tangerine         : constant Color;
   Auburn                   : constant Color;
   Aureolin                 : constant Color;
   Azure_mist               : constant Color;
   Baby_blue                : constant Color;
   Baby_pink                : constant Color;
   Battleship_grey          : constant Color;
   Beige                    : constant Color;
   Bistre                   : constant Color;
   Bittersweet              : constant Color;
   Blue_pigment             : constant Color;
   Blue_RYB                 : constant Color;
   Blue_green               : constant Color;
   Blue_violet              : constant Color;
   Bole                     : constant Color;
   Bondi_blue               : constant Color;
   Boston_University_Red    : constant Color;
   Brandeis_Blue            : constant Color;
   Brass                    : constant Color;
   Brick_red                : constant Color;
   Bright_cerulean          : constant Color;
   Bright_green             : constant Color;
   Bright_lavender          : constant Color;
   Bright_maroon            : constant Color;
   Bright_pink              : constant Color;
   Bright_turquoise         : constant Color;
   Bright_ube               : constant Color;
   Brilliant_lavender       : constant Color;
   Brilliant_rose           : constant Color;
   Brink_Pink               : constant Color;
   British_racing_green     : constant Color;
   Bronze                   : constant Color;
   Brown                    : constant Color;
   Brown_web                : constant Color;
   Buff                     : constant Color;
   Bulgarian_rose           : constant Color;
   Burgundy                 : constant Color;
   Burnt_orange             : constant Color;
   Burnt_sienna             : constant Color;
   Burnt_umber              : constant Color;
   Byzantine                : constant Color;
   Byzantium                : constant Color;
   Cadet_blue               : constant Color;
   Cadmium_Green            : constant Color;
   Cadmium_Orange           : constant Color;
   Cadmium_Red              : constant Color;
   Cadmium_Yellow           : constant Color;
   Cambridge_Blue           : constant Color;
   Camel                    : constant Color;
   Camouflage_green         : constant Color;
   Canary_yellow            : constant Color;
   Candy_apple_red          : constant Color;
   Candy_pink               : constant Color;
   Caput_mortuum            : constant Color;
   Cardinal                 : constant Color;
   Carmine                  : constant Color;
   Carmine_pink             : constant Color;
   Carmine_red              : constant Color;
   Carnation_pink           : constant Color;
   Carnelian                : constant Color;
   Carolina_blue            : constant Color;
   Caribbean_green          : constant Color;
   Carrot_orange            : constant Color;
   Ceil                     : constant Color;
   Celadon                  : constant Color;
   Celestial_blue           : constant Color;
   Cerise                   : constant Color;
   Cerise_pink              : constant Color;
   Cerulean                 : constant Color;
   Cerulean_blue            : constant Color;
   Chamoisee                : constant Color;
   Champagne                : constant Color;
   Charcoal                 : constant Color;
   Chartreuse_web           : constant Color;
   Cherry_blossom_pink      : constant Color;
   Chestnut                 : constant Color;
   Chocolate                : constant Color;
   Chrome_yellow            : constant Color;
   Cinereous                : constant Color;
   Cinnabar                 : constant Color;
   Cinnamon                 : constant Color;
   Citrine                  : constant Color;
   Classic_rose             : constant Color;
   Cobalt                   : constant Color;
   Columbia_blue            : constant Color;
   Cool_black               : constant Color;
   Cool_grey                : constant Color;
   Copper                   : constant Color;
   Copper_rose              : constant Color;
   Coquelicot               : constant Color;
   Coral                    : constant Color;
   Coral_pink               : constant Color;
   Coral_red                : constant Color;
   Cordovan                 : constant Color;
   Corn                     : constant Color;
   Cornsilk                 : constant Color;
   Cornflower_blue          : constant Color;
   Cosmic_latte             : constant Color;
   Cotton_candy             : constant Color;
   Cream                    : constant Color;
   Crimson                  : constant Color;
   Crimson_glory            : constant Color;
   Cyan_process             : constant Color;
   Dandelion                : constant Color;
   Dark_blue                : constant Color;
   Dark_brown               : constant Color;
   Dark_byzantium           : constant Color;
   Dark_candy_apple_red     : constant Color;
   Dark_cerulean            : constant Color;
   Dark_champagne           : constant Color;
   Dark_chestnut            : constant Color;
   Dark_coral               : constant Color;
   Dark_cyan                : constant Color;
   Dark_electric_blue       : constant Color;
   Dark_goldenrod           : constant Color;
   Dark_green               : constant Color;
   Dark_jungle_green        : constant Color;
   Dark_khaki               : constant Color;
   Dark_lava                : constant Color;
   Dark_lavender            : constant Color;
   Dark_magenta             : constant Color;
   Dark_midnight_blue       : constant Color;
   Dark_orange              : constant Color;
   Dark_pastel_green        : constant Color;
   Dark_pink                : constant Color;
   Dark_powder_blue         : constant Color;
   Dark_raspberry           : constant Color;
   Dark_red                 : constant Color;
   Dark_salmon              : constant Color;
   Dark_scarlet             : constant Color;
   Dark_sienna              : constant Color;
   Dark_slate_gray          : constant Color;
   Dark_spring_green        : constant Color;
   Dark_tan                 : constant Color;
   Dark_tangerine           : constant Color;
   Dark_taupe               : constant Color;
   Dark_terra_cotta         : constant Color;
   Dark_turquoise           : constant Color;
   Dark_violet              : constant Color;
   Dartmouth_green          : constant Color;
   Davys_grey               : constant Color;
   Deep_carmine             : constant Color;
   Deep_carmine_pink        : constant Color;
   Deep_carrot_orange       : constant Color;
   Deep_cerise              : constant Color;
   Deep_champagne           : constant Color;
   Deep_chestnut            : constant Color;
   Deep_fuchsia             : constant Color;
   Deep_jungle_green        : constant Color;
   Deep_lilac               : constant Color;
   Deep_magenta             : constant Color;
   Deep_peach               : constant Color;
   Deep_pink                : constant Color;
   Deep_saffron             : constant Color;
   Deep_sky_blue            : constant Color;
   Denim                    : constant Color;
   Desert                   : constant Color;
   Desert_sand              : constant Color;
   Dim_gray                 : constant Color;
   Dodger_blue              : constant Color;
   Dogwood_Rose             : constant Color;
   Drab                     : constant Color;
   Duke_blue                : constant Color;
   Earth_yellow             : constant Color;
   Ecru                     : constant Color;
   Eggplant                 : constant Color;
   Eggshell                 : constant Color;
   Egyptian_blue            : constant Color;
   Electric_blue            : constant Color;
   Electric_cyan            : constant Color;
   Electric_green           : constant Color;
   Electric_indigo          : constant Color;
   Electric_lavender        : constant Color;
   Electric_lime            : constant Color;
   Electric_purple          : constant Color;
   Electric_ultramarine     : constant Color;
   Electric_violet          : constant Color;
   Emerald                  : constant Color;
   Eton_blue                : constant Color;
   Fallow                   : constant Color;
   Falu_red                 : constant Color;
   Fandango                 : constant Color;
   Fashion_fuchsia          : constant Color;
   Fawn                     : constant Color;
   Feldgrau                 : constant Color;
   Fern_green               : constant Color;
   Field_drab               : constant Color;
   Firebrick                : constant Color;
   Fire_engine_red          : constant Color;
   Flame                    : constant Color;
   Flamingo_pink            : constant Color;
   Flavescent               : constant Color;
   Flax                     : constant Color;
   Forest_green             : constant Color;
   Forest_green_web         : constant Color;
   French_Beige             : constant Color;
   French_Rose              : constant Color;
   Fuchsia                  : constant Color;
   Fuchsia_Pink             : constant Color;
   Fulvous                  : constant Color;
   Gamboge                  : constant Color;
   Ghost_white              : constant Color;
   Glaucous                 : constant Color;
   Gold_metallic            : constant Color;
   Gold_web                 : constant Color;
   Golden_brown             : constant Color;
   Golden_poppy             : constant Color;
   Golden_yellow            : constant Color;
   Goldenrod                : constant Color;
   Gray                     : constant Color;
   Gray_asparagus           : constant Color;
   Green_web                : constant Color;
   Green_pigment            : constant Color;
   Green_RYB                : constant Color;
   Green_yellow             : constant Color;
   Grullo                   : constant Color;
   Halaya_ube               : constant Color;
   Han_Blue                 : constant Color;
   Han_Purple               : constant Color;
   Harlequin                : constant Color;
   Heliotrope               : constant Color;
   Hollywood_cerise         : constant Color;
   Honeydew                 : constant Color;
   Hot_magenta              : constant Color;
   Hot_pink                 : constant Color;
   Hunter_green             : constant Color;
   Iceberg                  : constant Color;
   Icterine                 : constant Color;
   India_green              : constant Color;
   Indian_yellow            : constant Color;
   Indigo                   : constant Color;
   Indigo_web               : constant Color;
   International_Klein_Blue : constant Color;
   International_orange     : constant Color;
   Iris                     : constant Color;
   Isabelline               : constant Color;
   Islamic_green            : constant Color;
   Ivory                    : constant Color;
   Jade                     : constant Color;
   Jazzberry_jam            : constant Color;
   Jonquil                  : constant Color;
   June_bud                 : constant Color;
   Jungle_green             : constant Color;
   Kelly_green              : constant Color;
   Khaki_web                : constant Color;
   Khaki                    : constant Color;
   Languid_lavender         : constant Color;
   Lava                     : constant Color;
   Lavender_floral          : constant Color;
   Lavender_web             : constant Color;
   Lavender_blue            : constant Color;
   Lavender_blush           : constant Color;
   Lavender_gray            : constant Color;
   Lavender_indigo          : constant Color;
   Lavender_magenta         : constant Color;
   Lavender_mist            : constant Color;
   Lavender_pink            : constant Color;
   Lavender_purple          : constant Color;
   Lavender_rose            : constant Color;
   Lawn_green               : constant Color;
   Lemon                    : constant Color;
   Lemon_chiffon            : constant Color;
   Light_apricot            : constant Color;
   Light_blue               : constant Color;
   Light_carmine_pink       : constant Color;
   Light_coral              : constant Color;
   Light_cornflower_blue    : constant Color;
   Light_fuchsia_pink       : constant Color;
   Light_khaki              : constant Color;
   Light_mauve              : constant Color;
   Light_pink               : constant Color;
   Light_sea_green          : constant Color;
   Light_salmon             : constant Color;
   Light_salmon_pink        : constant Color;
   Light_sky_blue           : constant Color;
   Light_slate_gray         : constant Color;
   Light_Thulian_pink       : constant Color;
   Lilac                    : constant Color;
   Lime                     : constant Color;
   Lime_web                 : constant Color;
   Lime_green               : constant Color;
   Linen                    : constant Color;
   Liver                    : constant Color;
   Lust                     : constant Color;
   Magenta_dye              : constant Color;
   Magenta_process          : constant Color;
   Magic_mint               : constant Color;
   Magnolia                 : constant Color;
   Mahogany                 : constant Color;
   Maize                    : constant Color;
   Majorelle_Blue           : constant Color;
   Malachite                : constant Color;
   Maroon_web               : constant Color;
   Maroon                   : constant Color;
   Mauve                    : constant Color;
   Mauve_taupe              : constant Color;
   Maya_blue                : constant Color;
   Medium_aquamarine        : constant Color;
   Medium_blue              : constant Color;
   Medium_candy_apple_red   : constant Color;
   Medium_carmine           : constant Color;
   Medium_champagne         : constant Color;
   Medium_electric_blue     : constant Color;
   Medium_jungle_green      : constant Color;
   Medium_lavender_magenta  : constant Color;
   Medium_Persian_blue      : constant Color;
   Medium_purple            : constant Color;
   Medium_red_violet        : constant Color;
   Medium_sea_green         : constant Color;
   Medium_spring_bud        : constant Color;
   Medium_spring_green      : constant Color;
   Medium_taupe             : constant Color;
   Medium_teal_blue         : constant Color;
   Medium_turquoise         : constant Color;
   Midnight_blue            : constant Color;
   Midnight_green           : constant Color;
   Eagle_green              : constant Color;
   Mikado_yellow            : constant Color;
   Mint_green               : constant Color;
   Misty_rose               : constant Color;
   Moccasin                 : constant Color;
   Mode_Beige               : constant Color;
   Mordant_red              : constant Color;
   Moss_green               : constant Color;
   Mountbatten_pink         : constant Color;
   Mulberry                 : constant Color;
   Mustard                  : constant Color;
   Myrtle                   : constant Color;
   MSU_Green                : constant Color;
   Nadeshiko_pink           : constant Color;
   Napier_Green             : constant Color;
   Naples_Yellow            : constant Color;
   Navajo_white             : constant Color;
   Navy_Blue                : constant Color;
   Ochre                    : constant Color;
   Office_green             : constant Color;
   Old_Gold                 : constant Color;
   Old_Lace                 : constant Color;
   Old_lavender             : constant Color;
   Old_Rose                 : constant Color;
   Olive                    : constant Color;
   Olive_Drab_web           : constant Color;
   Olive_Drab               : constant Color;
   Olivine                  : constant Color;
   Onyx                     : constant Color;
   Opera_mauve              : constant Color;
   Orange_color_wheel       : constant Color;
   Orange_RYB               : constant Color;
   Orange_web               : constant Color;
   Orange_peel              : constant Color;
   Orange_red               : constant Color;
   Orchid                   : constant Color;
   Oxford_Blue              : constant Color;
   OU_Crimson_Red           : constant Color;
   Pale_Amaranth_Pink       : constant Color;
   Pale_blue                : constant Color;
   Pale_brown               : constant Color;
   Pale_carmine             : constant Color;
   Pale_cerulean            : constant Color;
   Pale_chestnut            : constant Color;
   Pale_copper              : constant Color;
   Pale_cornflower_blue     : constant Color;
   Pale_gold                : constant Color;
   Pale_magenta             : constant Color;
   Pale_pink                : constant Color;
   Pale_red_violet          : constant Color;
   Pale_robin_egg_blue      : constant Color;
   Pale_silver              : constant Color;
   Pale_spring_bud          : constant Color;
   Pale_taupe               : constant Color;
   Palatinate_blue          : constant Color;
   Palatinate_purple        : constant Color;
   Pansy_purple             : constant Color;
   Papaya_whip              : constant Color;
   Pastel_green             : constant Color;
   Pastel_pink              : constant Color;
   Paynes_grey              : constant Color;
   Peach                    : constant Color;
   Peach_orange             : constant Color;
   Peach_puff               : constant Color;
   Peach_yellow             : constant Color;
   Pear                     : constant Color;
   Pearl                    : constant Color;
   Periwinkle               : constant Color;
   Persian_blue             : constant Color;
   Persian_green            : constant Color;
   Persian_indigo           : constant Color;
   Persian_orange           : constant Color;
   Persian_red              : constant Color;
   Persian_pink             : constant Color;
   Persian_rose             : constant Color;
   Persimmon                : constant Color;
   Phthalo_blue             : constant Color;
   Phthalo_green            : constant Color;
   Piggy_pink               : constant Color;
   Pine_green               : constant Color;
   Pink                     : constant Color;
   Pink_orange              : constant Color;
   Pistachio                : constant Color;
   Platinum                 : constant Color;
   Plum                     : constant Color;
   Portland_Orange          : constant Color;
   Powder_blue              : constant Color;
   Princeton_Orange         : constant Color;
   Prussian_blue            : constant Color;
   Psychedelic_purple       : constant Color;
   Puce                     : constant Color;
   Pumpkin                  : constant Color;
   Purple_web               : constant Color;
   Purple                   : constant Color;
   Purple_Heart             : constant Color;
   Purple_mountain_majesty  : constant Color;
   Purple_taupe             : constant Color;
   Radical_Red              : constant Color;
   Raspberry                : constant Color;
   Raspberry_glace          : constant Color;
   Raspberry_pink           : constant Color;
   Raspberry_rose           : constant Color;
   Raw_umber                : constant Color;
   Razzle_dazzle_rose       : constant Color;
   Razzmatazz               : constant Color;
   Red_pigment              : constant Color;
   Red_RYB                  : constant Color;
   Red_violet               : constant Color;
   Rich_black               : constant Color;
   Rich_brilliant_lavender  : constant Color;
   Rich_carmine             : constant Color;
   Rich_electric_blue       : constant Color;
   Rich_lavender            : constant Color;
   Rich_maroon              : constant Color;
   Rifle_green              : constant Color;
   Robin_egg_blue           : constant Color;
   Rose_Ebony               : constant Color;
   Rose_Gold                : constant Color;
   Rose_Madder              : constant Color;
   Rose_pink                : constant Color;
   Rose_quartz              : constant Color;
   Rose_taupe               : constant Color;
   Rose_vale                : constant Color;
   Rosewood                 : constant Color;
   Rosso_corsa              : constant Color;
   Rosy_brown               : constant Color;
   Royal_azure              : constant Color;
   Royal_blue               : constant Color;
   Royal_blue_web           : constant Color;
   Royal_fuchsia            : constant Color;
   Royal_purple             : constant Color;
   Ruby                     : constant Color;
   Rufous                   : constant Color;
   Russet                   : constant Color;
   Rust                     : constant Color;
   Sacramento_State_green   : constant Color;
   Saddle_brown             : constant Color;
   Safety_orange            : constant Color;
   blaze_orange             : constant Color;
   Saffron                  : constant Color;
   St_Patricks_blue         : constant Color;
   Salmon                   : constant Color;
   Salmon_pink              : constant Color;
   Sand                     : constant Color;
   Sand_dune                : constant Color;
   Sandy_brown              : constant Color;
   Sandy_taupe              : constant Color;
   Sangria                  : constant Color;
   Sap_green                : constant Color;
   Sapphire                 : constant Color;
   Satin_sheen_gold         : constant Color;
   Scarlet                  : constant Color;
   School_bus_yellow        : constant Color;
   Sea_green                : constant Color;
   Seal_brown               : constant Color;
   Seashell                 : constant Color;
   Selective_yellow         : constant Color;
   Sepia                    : constant Color;
   Shamrock_green           : constant Color;
   Shocking_pink            : constant Color;
   Sienna                   : constant Color;
   Silver                   : constant Color;
   Skobeloff                : constant Color;
   Sky_blue                 : constant Color;
   Sky_magenta              : constant Color;
   Slate_gray               : constant Color;
   Smalt                    : constant Color;
   Smoky_black              : constant Color;
   Snow                     : constant Color;
   Splashed_white           : constant Color;
   Spring_bud               : constant Color;
   Steel_blue               : constant Color;
   Straw                    : constant Color;
   Sunglow                  : constant Color;
   Sunset                   : constant Color;
   Tan                      : constant Color;
   Tangelo                  : constant Color;
   Tangerine                : constant Color;
   Tangerine_yellow         : constant Color;
   Taupe                    : constant Color;
   Taupe_gray               : constant Color;
   Tea_green                : constant Color;
   Tea_rose_orange          : constant Color;
   Tea_rose                 : constant Color;
   Teal                     : constant Color;
   Teal_blue                : constant Color;
   Tenne                    : constant Color;
   Tawny                    : constant Color;
   Terra_cotta              : constant Color;
   Thistle                  : constant Color;
   Thulian_pink             : constant Color;
   Tiffany_Blue             : constant Color;
   Tomato                   : constant Color;
   Torch_red                : constant Color;
   Tropical_rain_forest     : constant Color;
   Turkish_Rose             : constant Color;
   Turquoise                : constant Color;
   Turquoise_blue           : constant Color;
   Tuscan_red               : constant Color;
   Twilight_lavender        : constant Color;
   Tyrian_purple            : constant Color;
   Ube                      : constant Color;
   Ultramarine              : constant Color;
   Ultramarine_blue         : constant Color;
   Ultra_pink               : constant Color;
   Umber                    : constant Color;
   United_Nations_blue      : constant Color;
   Upsdell_red              : constant Color;
   UP_Forest_green          : constant Color;
   UP_Maroon                : constant Color;
   Vegas_Gold               : constant Color;
   Venetian_red             : constant Color;
   Vermilion                : constant Color;
   Violet_web               : constant Color;
   Violet_RYB               : constant Color;
   Viridian                 : constant Color;
   Vivid_auburn             : constant Color;
   Vivid_burgundy           : constant Color;
   Vivid_violet             : constant Color;
   Warm_black               : constant Color;
   Wenge                    : constant Color;
   Wheat                    : constant Color;
   White_smoke              : constant Color;
   Wild_blue_yonder         : constant Color;
   Wisteria                 : constant Color;
   Xanadu                   : constant Color;
   Yale_Blue                : constant Color;
   Yellow_process           : constant Color;
   Yellow_RYB               : constant Color;
   Yellow_green             : constant Color;



private

   White        : constant Color := to_Color (1.0,  1.0,  1.0);
   Black        : constant Color := to_Color (0.0,  0.0,  0.0);
   Grey         : constant Color := to_Color (0.5,  0.5,  0.5);

   Red          : constant Color := to_Color (1.0,  0.0,  0.0);
   Green        : constant Color := to_Color (0.0,  1.0,  0.0);
   Blue         : constant Color := to_Color (0.0,  0.0,  1.0);

   Yellow       : constant Color := to_Color (1.0,  1.0,  0.0);
   Cyan         : constant Color := to_Color (0.0,  1.0,  1.0);
   Magenta      : constant Color := to_Color (1.0,  0.0,  1.0);

   Azure        : constant Color :=  (  0,  127,  255);
   Violet       : constant Color :=  (139,    0,  255);
   Rose         : constant Color :=  (255,    0,  127);
   Orange       : constant Color :=  (255,  127,    0);
   Chartreuse   : constant Color :=  (223,  255,    0);
   spring_Green : constant Color :=  (  0,  255,  127);

   Air_Force_blue           : constant Color := (93, 138, 168);
   Alice_blue               : constant Color := (240, 248, 255);
   Alizarin                 : constant Color := (227, 38, 54);
   Amaranth                 : constant Color := (229, 43, 80);
   Amaranth_cerise          : constant Color := (205, 38, 130);
   Amaranth_deep_purple     : constant Color := (159, 43, 104);
   Amaranth_magenta         : constant Color := (237, 60, 202);
   Amaranth_pink            : constant Color := (241, 156, 187);
   Amaranth_purple          : constant Color := (171, 39, 79);
   Amber                    : constant Color := (255, 191, 0);
   Amber_SAE_ECE            : constant Color := (255, 126, 0);
   American_rose            : constant Color := (255, 3, 62);
   Amethyst                 : constant Color := (153, 102, 204);
   Android_Green            : constant Color := (164, 198, 57);
   Anti_flash_white         : constant Color := (242, 243, 244);
   Antique_fuchsia          : constant Color := (145, 92, 131);
   Antique_white            : constant Color := (250, 235, 215);
   Apple_green              : constant Color := (141, 182, 0);
   Apricot                  : constant Color := (251, 206, 177);
   Aqua                     : constant Color := (0, 255, 255);
   Aquamarine               : constant Color := (127, 255, 212);
   Army_green               : constant Color := (75, 83, 32);
   Arsenic                  : constant Color := (59, 68, 75);
   Ash_grey                 : constant Color := (178, 190, 181);
   Asparagus                : constant Color := (135, 169, 107);
   Atomic_tangerine         : constant Color := (255, 153, 102);
   Auburn                   : constant Color := (109, 53, 26);
   Aureolin                 : constant Color := (253, 238, 0);
   Azure_mist               : constant Color := (240, 255, 255);

   Baby_blue                : constant Color := (224, 255, 255);
   Baby_pink                : constant Color := (244, 194, 194);
   Battleship_grey          : constant Color := (132, 132, 130);
   Beige                    : constant Color := (245, 245, 220);
   Bistre                   : constant Color := (61, 43, 31);
   Bittersweet              : constant Color := (254, 111, 94);
   Blue_pigment             : constant Color := (51, 51, 153);
   Blue_RYB                 : constant Color := (2, 71, 254);
   Blue_green               : constant Color := (0, 221, 221);
   Blue_violet              : constant Color := (138, 43, 226);
   Bole                     : constant Color := (121, 68, 59);
   Bondi_blue               : constant Color := (0, 149, 182);
   Boston_University_Red    : constant Color := (204, 0, 0);
   Brandeis_Blue            : constant Color := (0, 112, 255);
   Brass                    : constant Color := (181, 166, 66);
   Brick_red                : constant Color := (203, 65, 84);
   Bright_cerulean          : constant Color := (29, 172, 214);
   Bright_green             : constant Color := (102, 255, 0);
   Bright_lavender          : constant Color := (191, 148, 228);
   Bright_maroon            : constant Color := (195, 33, 72);
   Bright_pink              : constant Color := (255, 0, 127);
   Bright_turquoise         : constant Color := (8, 232, 222);
   Bright_ube               : constant Color := (209, 159, 232);
   Brilliant_lavender       : constant Color := (244, 187, 255);
   Brilliant_rose           : constant Color := (255, 85, 163);
   Brink_Pink               : constant Color := (251, 96, 127);
   British_racing_green     : constant Color := (0, 66, 37);
   Bronze                   : constant Color := (205, 127, 50);
   Brown                    : constant Color := (150, 75, 0);
   Brown_web                : constant Color := (165, 42, 42);
   Buff                     : constant Color := (240, 220, 130);
   Bulgarian_rose           : constant Color := (72, 6, 7);
   Burgundy                 : constant Color := (128, 0, 32);
   Burnt_orange             : constant Color := (204, 85, 0);
   Burnt_sienna             : constant Color := (233, 116, 81);
   Burnt_umber              : constant Color := (138, 51, 36);
   Byzantine                : constant Color := (189, 51, 164);
   Byzantium                : constant Color := (112, 41, 99);

   Cadet_blue               : constant Color := (95, 158, 160);
   Cadmium_Green            : constant Color := (0, 107, 60);
   Cadmium_Orange           : constant Color := (237, 135, 45);
   Cadmium_Red              : constant Color := (227, 0, 34);
   Cadmium_Yellow           : constant Color := (255, 246, 0);
   Cambridge_Blue           : constant Color := (153, 204, 204);
   Camel                    : constant Color := (193, 154, 107);
   Camouflage_green         : constant Color := (120, 134, 107);
   Canary_yellow            : constant Color := (255, 239, 0);
   Candy_apple_red          : constant Color := (255, 8, 0);
   Candy_pink               : constant Color := (228, 113, 122);
   Caput_mortuum            : constant Color := (89, 39, 32);
   Cardinal                 : constant Color := (196, 30, 58);
   Carmine                  : constant Color := (150, 0, 24);
   Carmine_pink             : constant Color := (235, 76, 66);
   Carmine_red              : constant Color := (255, 0, 51);
   Carnation_pink           : constant Color := (255, 166, 201);
   Carnelian                : constant Color := (179, 27, 27);
   Carolina_blue            : constant Color := (153, 186, 227);
   Caribbean_green          : constant Color := (0, 204, 153);
   Carrot_orange            : constant Color := (237, 145, 33);
   Ceil                     : constant Color := (147, 162, 208);
   Celadon                  : constant Color := (172, 225, 175);
   Celestial_blue           : constant Color := (73, 151, 208);
   Cerise                   : constant Color := (222, 49, 99);
   Cerise_pink              : constant Color := (236, 59, 131);
   Cerulean                 : constant Color := (0, 123, 167);
   Cerulean_blue            : constant Color := (42, 82, 190);
   Chamoisee                : constant Color := (160, 120, 90);
   Champagne                : constant Color := (247, 231, 206);
   Charcoal                 : constant Color := (54, 69, 79);
   Chartreuse_web           : constant Color := (127, 255, 0);
   Cherry_blossom_pink      : constant Color := (255, 183, 197);
   Chestnut                 : constant Color := (205, 92, 92);
   Chocolate                : constant Color := (123, 63, 0);
   Chrome_yellow            : constant Color := (255, 167, 0);
   Cinereous                : constant Color := (152, 129, 123);
   Cinnabar                 : constant Color := (227, 66, 52);
   Cinnamon                 : constant Color := (210, 105, 30);
   Citrine                  : constant Color := (228, 208, 10);
   Classic_rose             : constant Color := (251, 204, 231);
   Cobalt                   : constant Color := (0, 71, 171);
   Columbia_blue            : constant Color := (155, 221, 255);
   Cool_black               : constant Color := (0, 46, 99);
   Cool_grey                : constant Color := (140, 146, 172);
   Copper                   : constant Color := (184, 115, 51);
   Copper_rose              : constant Color := (153, 102, 102);
   Coquelicot               : constant Color := (255, 56, 0);
   Coral                    : constant Color := (255, 127, 80);
   Coral_pink               : constant Color := (248, 131, 121);
   Coral_red                : constant Color := (255, 64, 64);
   Cordovan                 : constant Color := (137, 63, 69);
   Corn                     : constant Color := (251, 236, 93);
   Cornsilk                 : constant Color := (255, 248, 220);
   Cornflower_blue          : constant Color := (100, 149, 237);
   Cosmic_latte             : constant Color := (255, 248, 231);
   Cotton_candy             : constant Color := (255, 188, 217);
   Cream                    : constant Color := (255, 253, 208);
   Crimson                  : constant Color := (220, 20, 60);
   Crimson_glory            : constant Color := (190, 0, 50);
   Cyan_process             : constant Color := (0, 183, 235);

   Dandelion                : constant Color := (240, 225, 48);
   Dark_blue                : constant Color := (0, 0, 139);
   Dark_brown               : constant Color := (101, 67, 33);
   Dark_byzantium           : constant Color := (93, 57, 84);
   Dark_candy_apple_red     : constant Color := (164, 0, 0);
   Dark_cerulean            : constant Color := (8, 69, 126);
   Dark_champagne           : constant Color := (194, 178, 128);
   Dark_chestnut            : constant Color := (152, 105, 96);
   Dark_coral               : constant Color := (205, 91, 69);
   Dark_cyan                : constant Color := (0, 139, 139);
   Dark_electric_blue       : constant Color := (83, 104, 120);
   Dark_goldenrod           : constant Color := (184, 134, 11);
   Dark_green               : constant Color := (1, 50, 32);
   Dark_jungle_green        : constant Color := (26, 36, 33);
   Dark_khaki               : constant Color := (189, 183, 107);
   Dark_lava                : constant Color := (72, 60, 50);
   Dark_lavender            : constant Color := (115, 79, 150);
   Dark_magenta             : constant Color := (139, 0, 139);
   Dark_midnight_blue       : constant Color := (0, 51, 102);
   Dark_orange              : constant Color := (255, 140, 0);
   Dark_pastel_green        : constant Color := (3, 192, 60);
   Dark_pink                : constant Color := (231, 84, 128);
   Dark_powder_blue         : constant Color := (0, 51, 153);
   Dark_raspberry           : constant Color := (135, 38, 87);
   Dark_red                 : constant Color := (139, 0, 0);
   Dark_salmon              : constant Color := (233, 150, 122);
   Dark_scarlet             : constant Color := (86, 3, 25);
   Dark_sienna              : constant Color := (60, 20, 20);
   Dark_slate_gray          : constant Color := (47, 79, 79);
   Dark_spring_green        : constant Color := (23, 114, 69);
   Dark_tan                 : constant Color := (145, 129, 81);
   Dark_tangerine           : constant Color := (255, 168, 18);
   Dark_taupe               : constant Color := (72, 60, 50);
   Dark_terra_cotta         : constant Color := (204, 78, 92);
   Dark_turquoise           : constant Color := (0, 206, 209);
   Dark_violet              : constant Color := (148, 0, 211);
   Dartmouth_green          : constant Color := (13, 128, 15);
   Davys_grey               : constant Color := (85, 85, 85);
   Deep_carmine             : constant Color := (169, 32, 62);
   Deep_carmine_pink        : constant Color := (239, 48, 56);
   Deep_carrot_orange       : constant Color := (233, 105, 44);
   Deep_cerise              : constant Color := (218, 50, 135);
   Deep_champagne           : constant Color := (250, 214, 165);
   Deep_chestnut            : constant Color := (185, 78, 72);
   Deep_fuchsia             : constant Color := (193, 84, 193);
   Deep_jungle_green        : constant Color := (0, 75, 73);
   Deep_lilac               : constant Color := (153, 85, 187);
   Deep_magenta             : constant Color := (205, 0, 204);
   Deep_peach               : constant Color := (255, 203, 164);
   Deep_pink                : constant Color := (255, 20, 147);
   Deep_saffron             : constant Color := (255, 153, 51);
   Deep_sky_blue            : constant Color := (0, 191, 255);
   Denim                    : constant Color := (21, 96, 189);
   Desert                   : constant Color := (193, 154, 107);
   Desert_sand              : constant Color := (237, 201, 175);
   Dim_gray                 : constant Color := (105, 105, 105);
   Dodger_blue              : constant Color := (30, 144, 255);
   Dogwood_Rose             : constant Color := (215, 24, 104);
   Drab                     : constant Color := (150, 113, 23);
   Duke_blue                : constant Color := (0, 0, 156);

   Earth_yellow             : constant Color := (225, 169, 95);
   Ecru                     : constant Color := (194, 178, 128);
   Eggplant                 : constant Color := (97, 64, 81);
   Eggshell                 : constant Color := (240, 234, 214);
   Egyptian_blue            : constant Color := (16, 52, 166);
   Electric_blue            : constant Color := (125, 249, 255);
   Electric_cyan            : constant Color := (0, 255, 255);
   Electric_green           : constant Color := (0, 255, 0);
   Electric_indigo          : constant Color := (111, 0, 255);
   Electric_lavender        : constant Color := (244, 187, 255);
   Electric_lime            : constant Color := (204, 255, 0);
   Electric_purple          : constant Color := (191, 0, 255);
   Electric_ultramarine     : constant Color := (63, 0, 255);
   Electric_violet          : constant Color := (139, 0, 255);
   Emerald                  : constant Color := (80, 200, 120);
   Eton_blue                : constant Color := (150, 200, 162);

   Fallow                   : constant Color := (193, 154, 107);
   Falu_red                 : constant Color := (128, 24, 24);
   Fandango                 : constant Color := (184, 84, 137);
   Fashion_fuchsia          : constant Color := (244, 0, 161);
   Fawn                     : constant Color := (229, 170, 112);
   Feldgrau                 : constant Color := (77, 93, 83);
   Fern_green               : constant Color := (79, 121, 66);
   Field_drab               : constant Color := (108, 84, 30);
   Firebrick                : constant Color := (178, 34, 34);
   Fire_engine_red          : constant Color := (206, 22, 32);
   Flame                    : constant Color := (226, 88, 34);
   Flamingo_pink            : constant Color := (252, 142, 172);
   Flavescent               : constant Color := (247, 233, 142);
   Flax                     : constant Color := (238, 220, 130);
   Forest_green             : constant Color := (1, 68, 33);
   Forest_green_web         : constant Color := (34, 139, 34);
   French_Beige             : constant Color := (166, 123, 91);
   French_Rose              : constant Color := (246, 74, 138);
   Fuchsia                  : constant Color := (255, 0, 255);
   Fuchsia_Pink             : constant Color := (255, 119, 255);
   Fulvous                  : constant Color := (220, 132, 0);

   Gamboge                  : constant Color := (228, 155, 15);
   Ghost_white              : constant Color := (248, 248, 255);
   Glaucous                 : constant Color := (96, 130, 182);
   Gold_metallic            : constant Color := (212, 175, 55);
   Gold_web                 : constant Color := (255, 215, 0);
   Golden_brown             : constant Color := (153, 101, 21);
   Golden_poppy             : constant Color := (252, 194, 0);
   Golden_yellow            : constant Color := (255, 223, 0);
   Goldenrod                : constant Color := (218, 165, 32);
   Gray                     : constant Color := (128, 128, 128);
   Gray_asparagus           : constant Color := (70, 89, 69);
   Green_web                : constant Color := (0, 128, 0);
   Green_pigment            : constant Color := (0, 165, 80);
   Green_RYB                : constant Color := (102, 176, 50);
   Green_yellow             : constant Color := (173, 255, 47);
   Grullo                   : constant Color := (169, 154, 134);

   Halaya_ube               : constant Color := (102, 56, 84);
   Han_Blue                 : constant Color := (82, 24, 250);
   Han_Purple               : constant Color := (82, 24, 250);
   Harlequin                : constant Color := (63, 255, 0);
   Heliotrope               : constant Color := (223, 115, 255);
   Hollywood_cerise         : constant Color := (244, 0, 161);
   Honeydew                 : constant Color := (240, 255, 240);
   Hot_magenta              : constant Color := (255, 0, 204);
   Hot_pink                 : constant Color := (255, 105, 180);
   Hunter_green             : constant Color := (53, 94, 59);

   Iceberg                  : constant Color := (113, 166, 210);
   Icterine                 : constant Color := (252, 247, 94);
   India_green              : constant Color := (19, 136, 8);
   Indian_yellow            : constant Color := (227, 168, 87);
   Indigo                   : constant Color := (0, 65, 106);
   Indigo_web               : constant Color := (75, 0, 130);
   International_Klein_Blue : constant Color := (0, 47, 167);
   International_orange     : constant Color := (255, 79, 0);
   Iris                     : constant Color := (90, 79, 207);
   Isabelline               : constant Color := (244, 240, 236);
   Islamic_green            : constant Color := (0, 144, 0);
   Ivory                    : constant Color := (255, 255, 240);

   Jade                     : constant Color := (0, 168, 107);
   Jazzberry_jam            : constant Color := (165, 11, 94);
   Jonquil                  : constant Color := (250, 218, 94);
   June_bud                 : constant Color := (189, 218, 87);
   Jungle_green             : constant Color := (41, 171, 135);

   Kelly_green              : constant Color := (76, 187, 23);
   Khaki_web                : constant Color := (195, 176, 145);
   Khaki                    : constant Color := (240, 230, 140);

   Languid_lavender         : constant Color := (214, 202, 221);
   Lava                     : constant Color := (207, 16, 32);
   Lavender_floral          : constant Color := (181, 126, 220);
   Lavender_web             : constant Color := (230, 230, 250);
   Lavender_blue            : constant Color := (204, 204, 255);
   Lavender_blush           : constant Color := (255, 240, 245);
   Lavender_gray            : constant Color := (196, 195, 208);
   Lavender_indigo          : constant Color := (148, 87, 235);
   Lavender_magenta         : constant Color := (238, 130, 238);
   Lavender_mist            : constant Color := (230, 230, 250);
   Lavender_pink            : constant Color := (251, 174, 210);
   Lavender_purple          : constant Color := (150, 123, 182);
   Lavender_rose            : constant Color := (251, 160, 227);
   Lawn_green               : constant Color := (124, 252, 0);
   Lemon                    : constant Color := (255, 247, 0);
   Lemon_chiffon            : constant Color := (255, 250, 205);
   Light_apricot            : constant Color := (253, 213, 177);
   Light_blue               : constant Color := (173, 216, 230);
   Light_carmine_pink       : constant Color := (230, 103, 97);
   Light_coral              : constant Color := (240, 128, 128);
   Light_cornflower_blue    : constant Color := (173, 216, 230);
   Light_fuchsia_pink       : constant Color := (249, 132, 229);
   Light_khaki              : constant Color := (240, 230, 140);
   Light_mauve              : constant Color := (220, 208, 255);
   Light_pink               : constant Color := (255, 182, 193);
   Light_sea_green          : constant Color := (32, 178, 170);
   Light_salmon             : constant Color := (255, 160, 122);
   Light_salmon_pink        : constant Color := (255, 153, 153);
   Light_sky_blue           : constant Color := (135, 206, 250);
   Light_slate_gray         : constant Color := (119, 136, 153);
   Light_Thulian_pink       : constant Color := (230, 143, 172);
   Lilac                    : constant Color := (200, 162, 200);
   Lime                     : constant Color := (191, 255, 0);
   Lime_web                 : constant Color := (0, 255, 0);
   Lime_green               : constant Color := (50, 205, 50);
   Linen                    : constant Color := (250, 240, 230);
   Liver                    : constant Color := (83, 75, 79);
   Lust                     : constant Color := (230, 32, 32);

   Magenta_dye              : constant Color := (202, 21, 123);
   Magenta_process          : constant Color := (255, 0, 144);
   Magic_mint               : constant Color := (170, 240, 209);
   Magnolia                 : constant Color := (248, 244, 255);
   Mahogany                 : constant Color := (192, 64, 0);
   Maize                    : constant Color := (251, 236, 94);
   Majorelle_Blue           : constant Color := (96, 80, 220);
   Malachite                : constant Color := (11, 218, 81);
   Maroon_web               : constant Color := (128, 0, 0);
   Maroon                   : constant Color := (176, 48, 96);
   Mauve                    : constant Color := (224, 176, 255);
   Mauve_taupe              : constant Color := (145, 95, 109);
   Maya_blue                : constant Color := (115, 194, 251);
   Medium_aquamarine        : constant Color := (0, 84, 180);
   Medium_blue              : constant Color := (0, 0, 205);
   Medium_candy_apple_red   : constant Color := (226, 6, 44);
   Medium_carmine           : constant Color := (175, 64, 53);
   Medium_champagne         : constant Color := (243, 229, 171);
   Medium_electric_blue     : constant Color := (3, 80, 150);
   Medium_jungle_green      : constant Color := (28, 53, 45);
   Medium_lavender_magenta  : constant Color := (204, 153, 204);
   Medium_Persian_blue      : constant Color := (0, 103, 165);
   Medium_purple            : constant Color := (147, 112, 219);
   Medium_red_violet        : constant Color := (187, 51, 133);
   Medium_sea_green         : constant Color := (60, 179, 113);
   Medium_spring_bud        : constant Color := (201, 220, 137);
   Medium_spring_green      : constant Color := (0, 250, 154);
   Medium_taupe             : constant Color := (103, 76, 71);
   Medium_teal_blue         : constant Color := (0, 84, 180);
   Medium_turquoise         : constant Color := (72, 209, 204);
   Midnight_blue            : constant Color := (25, 25, 112);
   Midnight_green           : constant Color := (0, 73, 83);
   Eagle_green              : constant Color := (0, 73, 83);
   Mikado_yellow            : constant Color := (255, 196, 12);
   Mint_green               : constant Color := (152, 255, 152);
   Misty_rose               : constant Color := (255, 228, 225);
   Moccasin                 : constant Color := (250, 235, 215);
   Mode_Beige               : constant Color := (150, 113, 23);
   Mordant_red              : constant Color := (174, 12, 0);
   Moss_green               : constant Color := (173, 223, 173);
   Mountbatten_pink         : constant Color := (153, 122, 141);
   Mulberry                 : constant Color := (197, 75, 140);
   Mustard                  : constant Color := (255, 219, 88);
   Myrtle                   : constant Color := (33, 66, 30);
   MSU_Green                : constant Color := (0, 102, 51);

   Nadeshiko_pink           : constant Color := (246, 173, 198);
   Napier_Green             : constant Color := (42, 128, 0);
   Naples_Yellow            : constant Color := (250, 218, 94);
   Navajo_white             : constant Color := (255, 222, 173);
   Navy_Blue                : constant Color := (0, 0, 128);

   Ochre                    : constant Color := (204, 119, 34);
   Office_green             : constant Color := (0, 128, 0);
   Old_Gold                 : constant Color := (207, 181, 59);
   Old_Lace                 : constant Color := (253, 245, 230);
   Old_lavender             : constant Color := (121, 104, 120);
   Old_Rose                 : constant Color := (192, 128, 129);
   Olive                    : constant Color := (128, 128, 0);
   Olive_Drab_web           : constant Color := (107, 142, 35);
   Olive_Drab               : constant Color := (60, 52, 31);
   Olivine                  : constant Color := (154, 185, 115);
   Onyx                     : constant Color := (15, 15, 15);
   Opera_mauve              : constant Color := (183, 132, 167);
   Orange_color_wheel       : constant Color := (255, 127, 0);
   Orange_RYB               : constant Color := (251, 153, 2);
   Orange_web               : constant Color := (255, 165, 0);
   Orange_peel              : constant Color := (255, 159, 0);
   Orange_red               : constant Color := (255, 69, 0);
   Orchid                   : constant Color := (218, 112, 214);
   Oxford_Blue              : constant Color := (0, 33, 71);
   OU_Crimson_Red           : constant Color := (153, 0, 0);

   Pale_Amaranth_Pink       : constant Color := (221, 190, 195);
   Pale_blue                : constant Color := (175, 238, 238);
   Pale_brown               : constant Color := (152, 118, 84);
   Pale_carmine             : constant Color := (175, 64, 53);
   Pale_cerulean            : constant Color := (155, 196, 226);
   Pale_chestnut            : constant Color := (221, 173, 175);
   Pale_copper              : constant Color := (218, 138, 103);
   Pale_cornflower_blue     : constant Color := (171, 205, 239);
   Pale_gold                : constant Color := (230, 190, 138);
   Pale_magenta             : constant Color := (249, 132, 229);
   Pale_pink                : constant Color := (250, 218, 221);
   Pale_red_violet          : constant Color := (219, 112, 147);
   Pale_robin_egg_blue      : constant Color := (150, 222, 209);
   Pale_silver              : constant Color := (201, 192, 187);
   Pale_spring_bud          : constant Color := (236, 235, 189);
   Pale_taupe               : constant Color := (188, 152, 126);
   Palatinate_blue          : constant Color := (39, 59, 226);
   Palatinate_purple        : constant Color := (104, 40, 96);
   Pansy_purple             : constant Color := (120, 24, 74);
   Papaya_whip              : constant Color := (255, 239, 213);
   Pastel_green             : constant Color := (119, 221, 119);
   Pastel_pink              : constant Color := (255, 209, 220);
   Paynes_grey              : constant Color := (64, 64, 72);
   Peach                    : constant Color := (255, 229, 180);
   Peach_orange             : constant Color := (255, 204, 153);
   Peach_puff               : constant Color := (255, 218, 185);
   Peach_yellow             : constant Color := (250, 223, 173);
   Pear                     : constant Color := (209, 226, 49);
   Pearl                    : constant Color := (240, 234, 214);
   Periwinkle               : constant Color := (204, 204, 255);
   Persian_blue             : constant Color := (28, 57, 187);
   Persian_green            : constant Color := (0, 166, 147);
   Persian_indigo           : constant Color := (50, 18, 122);
   Persian_orange           : constant Color := (217, 144, 88);
   Persian_red              : constant Color := (204, 51, 51);
   Persian_pink             : constant Color := (247, 127, 190);
   Persian_rose             : constant Color := (254, 40, 162);
   Persimmon                : constant Color := (236, 88, 0);
   Phthalo_blue             : constant Color := (0, 15, 137);
   Phthalo_green            : constant Color := (18, 53, 36);
   Piggy_pink               : constant Color := (253, 221, 230);
   Pine_green               : constant Color := (1, 121, 111);
   Pink                     : constant Color := (255, 192, 203);
   Pink_orange              : constant Color := (255, 153, 102);
   Pistachio                : constant Color := (147, 197, 114);
   Platinum                 : constant Color := (229, 228, 226);
   Plum                     : constant Color := (204, 153, 204);
   Portland_Orange          : constant Color := (255, 90, 54);
   Powder_blue              : constant Color := (176, 224, 230);
   Princeton_Orange         : constant Color := (215, 71, 33);
   Prussian_blue            : constant Color := (0, 49, 83);
   Psychedelic_purple       : constant Color := (221, 0, 255);
   Puce                     : constant Color := (204, 136, 153);
   Pumpkin                  : constant Color := (255, 117, 24);
   Purple_web               : constant Color := (127, 0, 127);
   Purple                   : constant Color := (160, 92, 240);
   Purple_Heart             : constant Color := (105, 53, 156);
   Purple_mountain_majesty  : constant Color := (150, 120, 182);
   Purple_taupe             : constant Color := (80, 64, 77);

   Radical_Red              : constant Color := (255, 53, 94);
   Raspberry                : constant Color := (227, 11, 92);
   Raspberry_glace          : constant Color := (145, 95, 109);
   Raspberry_pink           : constant Color := (226, 80, 155);
   Raspberry_rose           : constant Color := (179, 68, 108);
   Raw_umber                : constant Color := (130, 102, 68);
   Razzle_dazzle_rose       : constant Color := (255, 51, 204);
   Razzmatazz               : constant Color := (227, 37, 107);
   Red_pigment              : constant Color := (237, 28, 36);
   Red_RYB                  : constant Color := (254, 39, 18);
   Red_violet               : constant Color := (199, 21, 133);
   Rich_black               : constant Color := (0, 64, 64);
   Rich_brilliant_lavender  : constant Color := (241, 167, 254);
   Rich_carmine             : constant Color := (215, 0, 64);
   Rich_electric_blue       : constant Color := (8, 146, 208);
   Rich_lavender            : constant Color := (170, 97, 204);
   Rich_maroon              : constant Color := (176, 48, 96);
   Rifle_green              : constant Color := (65, 72, 51);
   Robin_egg_blue           : constant Color := (0, 204, 204);
   Rose_Ebony               : constant Color := (103, 76, 71);
   Rose_Gold                : constant Color := (183, 110, 121);
   Rose_Madder              : constant Color := (227, 38, 54);
   Rose_pink                : constant Color := (255, 102, 204);
   Rose_quartz              : constant Color := (170, 152, 169);
   Rose_taupe               : constant Color := (144, 93, 93);
   Rose_vale                : constant Color := (171, 78, 82);
   Rosewood                 : constant Color := (101, 0, 11);
   Rosso_corsa              : constant Color := (212, 0, 0);
   Rosy_brown               : constant Color := (188, 143, 143);
   Royal_azure              : constant Color := (0, 56, 168);
   Royal_blue               : constant Color := (0, 35, 102);
   Royal_blue_web           : constant Color := (65, 105, 225);
   Royal_fuchsia            : constant Color := (202, 44, 146);
   Royal_purple             : constant Color := (107, 63, 160);
   Ruby                     : constant Color := (224, 17, 95);
   Rufous                   : constant Color := (168, 28, 7);
   Russet                   : constant Color := (128, 70, 27);
   Rust                     : constant Color := (183, 65, 14);

   Sacramento_State_green   : constant Color := (0, 86, 63);
   Saddle_brown             : constant Color := (139, 69, 19);
   Safety_orange            : constant Color := (255, 102, 0);
   blaze_orange             : constant Color := (255, 102, 0);
   Saffron                  : constant Color := (244, 196, 48);
   St_Patricks_blue         : constant Color := (35, 41, 122);
   Salmon                   : constant Color := (255, 140, 105);
   Salmon_pink              : constant Color := (255, 145, 164);
   Sand                     : constant Color := (194, 178, 128);
   Sand_dune                : constant Color := (150, 113, 23);
   Sandy_brown              : constant Color := (244, 164, 96);
   Sandy_taupe              : constant Color := (150, 113, 23);
   Sangria                  : constant Color := (146, 0, 10);
   Sap_green                : constant Color := (80, 125, 42);
   Sapphire                 : constant Color := (8, 37, 103);
   Satin_sheen_gold         : constant Color := (203, 161, 53);
   Scarlet                  : constant Color := (255, 32, 0);
   School_bus_yellow        : constant Color := (255, 216, 0);
   Sea_green                : constant Color := (46, 139, 87);
   Seal_brown               : constant Color := (50, 20, 20);
   Seashell                 : constant Color := (255, 245, 238);
   Selective_yellow         : constant Color := (255, 186, 0);
   Sepia                    : constant Color := (112, 66, 20);
   Shamrock_green           : constant Color := (0, 158, 96);
   Shocking_pink            : constant Color := (252, 15, 192);
   Sienna                   : constant Color := (136, 45, 23);
   Silver                   : constant Color := (192, 192, 192);
   Skobeloff                : constant Color := (0, 122, 116);
   Sky_blue                 : constant Color := (135, 206, 235);
   Sky_magenta              : constant Color := (207, 113, 175);
   Slate_gray               : constant Color := (112, 128, 144);
   Smalt                    : constant Color := (0, 51, 153);
   Smoky_black              : constant Color := (16, 12, 8);
   Snow                     : constant Color := (255, 250, 250);
   Splashed_white           : constant Color := (254, 253, 255);
   Spring_bud               : constant Color := (167, 252, 0);
   Steel_blue               : constant Color := (70, 130, 180);
   Straw                    : constant Color := (228, 117, 111);
   Sunglow                  : constant Color := (255, 204, 51);
   Sunset                   : constant Color := (250, 214, 165);

   Tan                      : constant Color := (210, 180, 140);
   Tangelo                  : constant Color := (249, 77, 0);
   Tangerine                : constant Color := (242, 133, 0);
   Tangerine_yellow         : constant Color := (255, 204, 0);
   Taupe                    : constant Color := (72, 60, 50);
   Taupe_gray               : constant Color := (139, 133, 137);
   Tea_green                : constant Color := (208, 240, 192);
   Tea_rose_orange          : constant Color := (248, 131, 121);
   Tea_rose                 : constant Color := (244, 194, 194);
   Teal                     : constant Color := (0, 128, 128);
   Teal_blue                : constant Color := (54, 117, 136);
   Tenne                    : constant Color := (205, 87, 0);
   Tawny                    : constant Color := (205, 87, 0);
   Terra_cotta              : constant Color := (226, 114, 91);
   Thistle                  : constant Color := (216, 191, 216);
   Thulian_pink             : constant Color := (222, 111, 161);
   Tiffany_Blue             : constant Color := (10, 186, 181);
   Tomato                   : constant Color := (255, 99, 71);
   Torch_red                : constant Color := (253, 14, 53);
   Tropical_rain_forest     : constant Color := (0, 117, 94);
   Turkish_Rose             : constant Color := (181, 114, 129);
   Turquoise                : constant Color := (48, 213, 200);
   Turquoise_blue           : constant Color := (0, 191, 255);
   Tuscan_red               : constant Color := (123, 54, 54);
   Twilight_lavender        : constant Color := (138, 73, 107);
   Tyrian_purple            : constant Color := (102, 2, 60);

   Ube                      : constant Color := (136, 120, 195);
   Ultramarine              : constant Color := (18, 10, 143);
   Ultramarine_blue         : constant Color := (65, 102, 245);
   Ultra_pink               : constant Color := (255, 111, 255);
   Umber                    : constant Color := (99, 81, 71);
   United_Nations_blue      : constant Color := (91, 146, 229);
   Upsdell_red              : constant Color := (174, 22, 32);
   UP_Forest_green          : constant Color := (1, 68, 33);
   UP_Maroon                : constant Color := (123, 17, 19);

   Vegas_Gold               : constant Color := (197, 179, 88);
   Venetian_red             : constant Color := (200, 8, 21);
   Vermilion                : constant Color := (227, 66, 51);
   Violet_wheel             : constant Color := (128, 0, 255);
   Violet_web               : constant Color := (238, 130, 238);
   Violet_RYB               : constant Color := (134, 1, 175);
   Viridian                 : constant Color := (64, 130, 109);
   Vivid_auburn             : constant Color := (147, 39, 36);
   Vivid_burgundy           : constant Color := (159, 29, 53);
   Vivid_violet             : constant Color := (153, 0, 255);

   Warm_black               : constant Color := (0, 66, 66);
   Wenge                    : constant Color := (100, 84, 82);
   Wheat                    : constant Color := (245, 222, 179);
   White_smoke              : constant Color := (245, 245, 245);
   Wild_blue_yonder         : constant Color := (162, 173, 208);
   Wisteria                 : constant Color := (201, 160, 220);

   Xanadu                   : constant Color := (115, 134, 120);

   Yale_Blue                : constant Color := (15, 77, 146);
   Yellow_process           : constant Color := (255, 239, 0);
   Yellow_RYB               : constant Color := (254, 254, 51);
   Yellow_green             : constant Color := (154, 205, 50);

end opengl.Palette;
